config/routes.rb
Rails.application.routes.draw do

  root to: "hobbies#index"
  devise_for :users

  resources :hobbies
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hobbies , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobbies, only: [:show, :edit, :update, :destroy]
  
  
  
  def index
    @hobbies = current_user.hobbies
  end

  def show
  end

  def new
    @hobby = Hobby.new
  end

  def create
    @hobby = current_user.hobbies.new(hobby_params)
    if @hobby.save 
      redirect_to hobbies_path
    else
      render :new
    end
  end

  def update
    if @hobby.update(hobby_params)
      redirect_to hobby_path
    else
      render :edit
    end
  end
  
  def edit
  end

  # def destroy
  #   @hobby = Hobby.find(hobby_params).destroy 
  #   redirect_to hobby_path
  # end

  def destroy
    @hobby.destroy
    redirect_to hobbies_path
  end

  private
  def hobby_params
    params.require(:hobby).permit(:name, :description)
  end

  def set_hobbies 
    @hobby = current_user.hobbies.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/views/hobbies/edit.html.erb
<%= form_with(model: @hobby, local: true) do |f| %>
  
  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
</div>  
  
  <div class='field'>
    <%= f.label :description %>
    <%= f.text_field :description %>
</div>  
  <%= f.submit %>
<% end %>

<%= link_to "Hobbies", hobbies%>


<%= link_to 'Destroy Page', @hobbies, method: :delete %>

app/views/hobbies/index.html.erb
<h1>Hobbies </h1>

<%= button_to "Log Out", destroy_user_session_path, method: :delete %>

<%= link_to "Add Hobbies", new_hobby_path %>
<h3>Your Hobbies</h3>
<ul>
  <% @hobbies.each do |hobby| %>
    <li>
      <%= hobby.name %> - <%= hobby.description %>
    </li>
 <%= link_to 'Delete Hobby', hobby_path(hobby), method: :delete%>
  <% end %>

</ul>

app/views/hobbies/new.html.erb
<h1>Add Hobby</h1>
<%= form_with(model: @hobby, local: true) do |f| %>
  
  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
</div>  
  
  <div class='field'>
    <%= f.label :description %>
    <%= f.text_field :description %>
</div>  
  <%= f.submit %>
<% end %>

<%= link_to "Hobbies", hobbies_path%>

app/views/hobbies/show.html.erb
<h1>Hobbies#show</h1>
<p>Find me in app/views/hobbies/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hobbies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>